baseURL = "https://renatoathaydes.github.io/rawhttp"
languageCode = "en-us"
title = "RawHTTP"
theme = "sam"
publishDir = "../public"

[params]
    footerText = "RawHTTP - a HTTP library for the JVM"
    description = "RawHTTP - a HTTP library for the JVM"

[[params.mainMenu]]
    link = "/rawhttp/in-5-minutes"
    text = "RawHTTP in 5 minutes"

[[params.mainMenu]]
    link = "/rawhttp/docs"
    text = "Documentation"

[[params.mainMenu]]
    link = "/rawhttp/rawhttp-modules"
    text = "Modules"

[[params.mainMenu]]
    link = "/rawhttp/about"
    text = "About"
